In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

### **Ejercicio N°4**

Teniendo en cuenta la variable `altura_m` que se encuentra en el dataset `pacientes.csv` trabajado en el **Ejercicio N°2**, genere una tabla de frecuencias en la que las observaciones se encuentren segmentadas en subintervalos de 10 cm de amplitud que estén “cerrados por izquierda”, es decir, que tengan la forma **[extremo_inferior, extremo_superior)**.

La tabla de frecuencias generada deberá contener columnas en las que se especifiquen las frecuencias absolutas, relativas y relativas acumuladas correspondientes a cada subintervalo.
¿Qué porcentaje de las personas del dataset tienen una altura **menor a 1.8 m**?

In [11]:
pacientes=pd.read_csv('./datasets/pacientes.csv', sep=';')
pacientes

,codigo_paciente,peso_inicial_kg,peso_final_kg,altura_m,sexo,tiempo_tratamiento_dias
0,398911,78,72,"1,8",F,583
1,398912,68,68,"1,75",F,159
2,398913,92,70,"1,85",F,70
3,398914,66,64,"1,65",M,41
4,398915,51,50,"1,55",F,30
5,398916,75,65,"1,7",M,313
6,398917,53,49,"1,51",M,220
7,398918,89,80,"1,77",M,92
8,398919,69,60,"1,7",F,488
9,398920,97,83,"1,78",M,579
10,398921,64,63,"1,64",F,217
11,398922,69,69,"1,7",F,181
12,398923,60,58,"1,52",M,460
13,398924,68,60,"1,65",F,659
14,398925,55,55,"1,65",F,334
15,398926,87,80,"1,73",M,335
16,398927,85,80,"1,8",M,401
17,398928,58,55,"1,5",M,191
18,398929,90,70,"1,6",F,297
19,398930,85,77,"1,65",F,702
20,398931,48,48,"1,5",F,575
21,398932,81,80,"1,82",M,247
22,398933,89,85,"1,82",F,444
23,398934,81,70,"1,69",M,284
24,398935,69,65,"1,6",F,706
25,398936,80,73,"1,65",F,339
26,398937,56,53,"1,59",M,46
27,398938,82,65,"1,6",M,347
28,398939,63,60,"1,66",F,707
29,398940,53,53,"1,65",F,461
30,398941,50,48,"1,5",F,375
31,398942,76,66,"1,71",M,247
32,398943,62,60,"1,65",F,492
33,398944,78,70,"1,77",F,192
34,398945,52,52,"1,53",F,568
35,398946,86,80,"1,85",M,60
36,398947,52,50,"1,5",M,88
37,398948,92,70,"1,9",M,356
38,398949,49,53,"1,5",M,132
39,398950,48,54,"1,5",M,286
40,398951,64,67,"1,69",M,426
41,398952,67,70,"1,66",F,702
42,398953,85,81,"1,83",F,64
43,398954,90,93,"1,9",F,537
44,398955,86,86,"1,79",F,184
45,398956,91,88,"1,77",F,373
46,398957,90,87,"1,6",F,351
47,398958,80,79,"1,5",F,249
48,398959,85,80,"1,76",M,619
49,398960,77,65,"1,64",M,89

In [12]:
pacientes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   codigo_paciente          50 non-null     int64
 1   peso_inicial_kg          50 non-null     int64
 2   peso_final_kg            50 non-null     int64
 3   altura_m                 50 non-null     object
 4   sexo                     50 non-null     object
 5   tiempo_tratamiento_dias  50 non-null     int64
dtypes: int64(4), object(2)
memory usage: 2.5+ KB

In [13]:
pacientes['altura_m'].unique().tolist()

['1,8',
 '1,75',
 '1,85',
 '1,65',
 '1,55',
 '1,7',
 '1,51',
 '1,77',
 '1,78',
 '1,64',
 '1,52',
 '1,73',
 '1,5',
 '1,6',
 '1,82',
 '1,69',
 '1,59',
 '1,66',
 '1,71',
 '1,53',
 '1,9',
 '1,83',
 '1,79',
 '1,76']

In [14]:
pacientes['altura_m']=pacientes['altura_m'].str.replace(',','.')

In [19]:
pacientes['altura_m']=pacientes['altura_m'].astype('float')

In [27]:
sep=np.arange(1.5,2.0,0.1)
pacientes['altura_bins']=pd.cut(pacientes['altura_m'],bins=sep,right=False)

In [25]:
pacientes

,codigo_paciente,peso_inicial_kg,peso_final_kg,altura_m,sexo,tiempo_tratamiento_dias,altura_bins
0,398911,78,72,1.80,F,583,"[1.7, 1.8)"
1,398912,68,68,1.75,F,159,"[1.7, 1.8)"
2,398913,92,70,1.85,F,70,"[1.8, 1.9)"
3,398914,66,64,1.65,M,41,"[1.6, 1.7)"
4,398915,51,50,1.55,F,30,"[1.5, 1.6)"
5,398916,75,65,1.70,M,313,"[1.6, 1.7)"
6,398917,53,49,1.51,M,220,"[1.5, 1.6)"
7,398918,89,80,1.77,M,92,"[1.7, 1.8)"
8,398919,69,60,1.70,F,488,"[1.6, 1.7)"
9,398920,97,83,1.78,M,579,"[1.7, 1.8)"
10,398921,64,63,1.64,F,217,"[1.6, 1.7)"
11,398922,69,69,1.70,F,181,"[1.6, 1.7)"
12,398923,60,58,1.52,M,460,"[1.5, 1.6)"
13,398924,68,60,1.65,F,659,"[1.6, 1.7)"
14,398925,55,55,1.65,F,334,"[1.6, 1.7)"
15,398926,87,80,1.73,M,335,"[1.7, 1.8)"
16,398927,85,80,1.80,M,401,"[1.7, 1.8)"
17,398928,58,55,1.50,M,191,"[1.5, 1.6)"
18,398929,90,70,1.60,F,297,"[1.6, 1.7)"
19,398930,85,77,1.65,F,702,"[1.6, 1.7)"
20,398931,48,48,1.50,F,575,"[1.5, 1.6)"
21,398932,81,80,1.82,M,247,"[1.8, 1.9)"
22,398933,89,85,1.82,F,444,"[1.8, 1.9)"
23,398934,81,70,1.69,M,284,"[1.6, 1.7)"
24,398935,69,65,1.60,F,706,"[1.6, 1.7)"
25,398936,80,73,1.65,F,339,"[1.6, 1.7)"
26,398937,56,53,1.59,M,46,"[1.5, 1.6)"
27,398938,82,65,1.60,M,347,"[1.6, 1.7)"
28,398939,63,60,1.66,F,707,"[1.6, 1.7)"
29,398940,53,53,1.65,F,461,"[1.6, 1.7)"
30,398941,50,48,1.50,F,375,"[1.5, 1.6)"
31,398942,76,66,1.71,M,247,"[1.7, 1.8)"
32,398943,62,60,1.65,F,492,"[1.6, 1.7)"
33,398944,78,70,1.77,F,192,"[1.7, 1.8)"
34,398945,52,52,1.53,F,568,"[1.5, 1.6)"
35,398946,86,80,1.85,M,60,"[1.8, 1.9)"
36,398947,52,50,1.50,M,88,"[1.5, 1.6)"
37,398948,92,70,1.90,M,356,"[1.8, 1.9)"
38,398949,49,53,1.50,M,132,"[1.5, 1.6)"
39,398950,48,54,1.50,M,286,"[1.5, 1.6)"
40,398951,64,67,1.69,M,426,"[1.6, 1.7)"
41,398952,67,70,1.66,F,702,"[1.6, 1.7)"
42,398953,85,81,1.83,F,64,"[1.8, 1.9)"
43,398954,90,93,1.90,F,537,"[1.8, 1.9)"
44,398955,86,86,1.79,F,184,"[1.7, 1.8)"
45,398956,91,88,1.77,F,373,"[1.7, 1.8)"
46,398957,90,87,1.60,F,351,"[1.6, 1.7)"
47,398958,80,79,1.50,F,249,"[1.5, 1.6)"
48,398959,85,80,1.76,M,619,"[1.7, 1.8)"
49,398960,77,65,1.64,M,89,"[1.6, 1.7)"

In [ ]:
frec_abs=pacientes['altura_bins'].value_counts().sort_index()
frec_rel=pacientes['altura_bins'].value_counts(normalize=True).sort_index()

In [46]:
tabla=pd.DataFrame({'Cantidad':frec_abs,
                    'Porcentaje':(frec_rel*100).round(2),
                    'Frecuencia relativa acumulada': frec_rel.cumsum()})
tabla

             Cantidad  Porcentaje  Frecuencia relativa acumulada
altura_bins
[1.5, 1.6)         12        24.0                           0.24
[1.6, 1.7)         20        40.0                           0.64
[1.7, 1.8)         11        22.0                           0.86
[1.8, 1.9)          7        14.0                           1.00

In [47]:
tabla = tabla.rename_axis('Intervalo de alturas')
tabla

                      Cantidad  Porcentaje  Frecuencia relativa acumulada
Intervalo de alturas
[1.5, 1.6)                  12        24.0                           0.24
[1.6, 1.7)                  20        40.0                           0.64
[1.7, 1.8)                  11        22.0                           0.86
[1.8, 1.9)                   7        14.0                           1.00

In [62]:
menos_180=(pacientes['altura_m']<1.80).sum()
print(f'Hay {menos_180} personas que miden menos de 1.80 m que representa un {menos_180*100/len(pacientes)} % del total')

Hay 41 personas que miden menos de 1.80 m que representa un 82.0 % del total