# **NOTEBOOK CLASE 2 UNIDAD 6 - FUNDAMENTOS DE CIENCIA DE DATOS**

## ***Ajustes y modelos: Regresión Lineal. Inferencia y predicción***

In [10]:
# Librerías
import pandas as pd
import statsmodels.formula.api as smf

In [7]:
# Datos
datos = pd.read_csv(ruta + '/datasets/advertising.csv')
datos.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

## 1. Calculá la matriz de correlaciones lineales entre todas las variables del dataset. ¿Qué predictores parecen estar más asociados con Sales?

In [8]:
# Matriz de correlación de Pearson
datos.corr()

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

## 2. Ajustá un modelo de regresión lineal múltiple para Sales usando los tres predictores: TV, Radio y Newspaper. ¿Cuáles predictores son estadísticamente significativos al 5%?

Inversión en TV y Radio

In [11]:
modelo1 = smf.ols(formula = 'Sales ~ TV + Radio +	Newspaper', data = datos).fit()
print(modelo1.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     605.4
Date:                Fri, 22 May 2026   Prob (F-statistic):           8.13e-99
Time:                        22:19:38   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             774.7
Df Residuals:                     196   BIC:                             787.9
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6251      0.308     15.041      0.000       4.019       5.232
TV             0.0544      0.001     39.592      0.000       0.052       0.057
Radio          0.1070      0.008     12.604      0.000       0.090       0.124
Newspaper      0.0003      0.006      0.058      0.954      -0.011       0.012
==============================================================================
Omnibus:                       16.081   Durbin-Watson:                   2.251
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.655
Skew:                          -0.431   Prob(JB):                     9.88e-07
Kurtosis:                       4.605   Cond. No.                         454.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

## 3. Reajustá el modelo eliminando el o los predictores no significativos. Usando el modelo reducido, estimá las ventas esperadas para un mercado con una inversión de 150 mil USD en TV, 30 mil USD en radio y 60 mil USD en periódicos.

In [12]:
modelo2 = smf.ols(formula = 'Sales ~ TV + Radio', data = datos).fit() # Ajustamos modelo reducido
print(modelo2.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Sales   R-squared:                       0.903
Model:                            OLS   Adj. R-squared:                  0.902
Method:                 Least Squares   F-statistic:                     912.7
Date:                Fri, 22 May 2026   Prob (F-statistic):          2.39e-100
Time:                        22:27:39   Log-Likelihood:                -383.34
No. Observations:                 200   AIC:                             772.7
Df Residuals:                     197   BIC:                             782.6
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept      4.6309      0.290     15.952      0.000       4.058       5.203
TV             0.0544      0.001     39.726      0.000       0.052       0.057
Radio          0.1072      0.008     13.522      0.000       0.092       0.123
==============================================================================
Omnibus:                       16.227   Durbin-Watson:                   2.252
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.973
Skew:                          -0.434   Prob(JB):                     8.43e-07
Kurtosis:                       4.613   Cond. No.                         425.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [14]:
# Predicción de ventas para un mercado
# con una inversión de 150 mil USD en TV, 30 mil USD en radio y 60 mil USD en periódicos.

datos_prediccion = pd.DataFrame({'TV' : [150],
                                 'Radio' : [30],
                                 'Newspaper' : [60]})
datos_prediccion

    TV  Radio  Newspaper
0  150     30         60

In [15]:
modelo2.predict(datos_prediccion) # 16 mil unidades vendidas

0    16.013461
dtype: float64

In [16]:
datos_prediccion2 = pd.DataFrame({'TV' : [150],
                                 'Radio' : [30],
                                 'Newspaper' : [15]})
datos_prediccion2

    TV  Radio  Newspaper
0  150     30         15

In [17]:
modelo2.predict(datos_prediccion2)

0    16.013461
dtype: float64